import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import ThemeProviderPage from './themeProvider';

const poppins = Poppins({ subsets: ['latin'], weight: '500' });

export const metadata: Metadata = {
  title: 'Rubeus Integração',
  description: 'Generated by Peixola',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${poppins.className} flex flex-col min-h-full min-w-full`}
      >
        <ThemeProviderPage>{children}</ThemeProviderPage>
      </body>
    </html>
  );
}
