export const dataservers = [
  {
    key: 'EduAlunoData',
    name: 'Alunos',
    code: 'EduAlunoData',
    label: 'EduAlunoData',
  },
  {
    key: 'EduInscAlunoAtvOfertadaData',
    name: 'Alunos inscritos por Atividade e Oferta',
    code: 'EduInscAlunoAtvOfertadaData',
    label: 'EduInscAlunoAtvOfertadaData',
  },
  {
    key: 'EduHistDiscFacData',
    name: 'Aproveitamento de estudo',
    code: 'EduHistDiscFacData',
    label: 'EduHistDiscFacData',
  },
  {
    key: 'EduBolsaData',
    name: 'Bolsas',
    code: 'EduBolsaData',
    label: 'EduBolsaData',
  },
  {
    key: 'EduBolsaAlunoData',
    name: 'Bolsas por Aluno',
    code: 'EduBolsaAlunoData',
    label: 'EduBolsaAlunoData',
  },
  {
    key: 'EduCampusData',
    name: 'Campus',
    code: 'EduCampusData',
    label: 'EduCampusData',
  },
  /* {
    key: 'FinCFODataBR',
    name: 'Cliente/Fornecedor',
    code: 'FinCFODataBR',
    label: 'FinCFODataBR',
  }, */
  {
    key: 'EduContratoData',
    name: 'Contratos',
    code: 'EduContratoData',
    label: 'EduContratoData',
  },
  {
    key: 'EduPSInscricaoAreaOfertadaData',
    name: 'Cria a inscrição',
    code: 'EduPSInscricaoAreaOfertadaData',
    label: 'EduPSInscricaoAreaOfertadaData',
  },
  {
    key: 'EduPSInscricaoUsuarioAreaData',
    name: 'Cria a inscrição e Usuário',
    code: 'EduPSInscricaoUsuarioAreaData',
    label: 'EduPSInscricaoUsuarioAreaData',
  },
  {
    key: 'EduHistDiscFacExtData',
    name: 'Disciplinas de origem',
    code: 'EduHistDiscFacExtData',
    label: 'EduHistDiscFacExtData',
  },
  {
    key: 'EduDisciplinaData',
    name: 'Documentos do Aluno',
    code: 'EduDOCALUNOData',
    label: 'EduDocAlunoData',
  },
  {
    key: 'EduDocFiadorData',
    name: 'Documentos do Fiador',
    code: 'EduDocFiadorData',
    label: 'EduDocFiadorData',
  },
  {
    key: 'EduPSDocumentoEntregueData',
    name: 'Documentos Entregues na inscrição',
    code: 'EduPSDocumentoEntregueData',
    label: 'EduPSDocumentoEntregueData',
  },
  {
    key: 'EduFichaMedicaAlunoData',
    name: 'Ficha Médica do Aluno',
    code: 'EduFichaMedicaAlunoData',
    label: 'EduFichaMedicaAlunoData',
  },
  {
    key: 'EduFiadorData',
    name: 'Fiadores',
    code: 'EduFiadorData',
    label: 'EduFiadorData',
  },
  {
    key: 'RhuFiliacaoData',
    name: 'Filiação',
    code: 'RhuFiliacaoData',
    label: 'RhuFiliacaoData',
  },
  {
    key: 'FinLANDataBR',
    name: 'Lançamentos',
    code: 'FinLANDataBR',
    label: 'FinLANDataBR',
  },
  {
    key: 'EduPSLocalEtapaInscritoData',
    name: 'Local e Etapa da Inscrição',
    code: 'EduPSLocalEtapaInscritoData',
    label: 'EduPSLocalEtapaInscritoData',
  },
  {
    key: 'EduMatricPLData',
    name: 'Matriculas no período letivo',
    code: 'EduMatricPLData',
    label: 'EduMatricPLData',
  },
  {
    key: 'EduParcelaData',
    name: 'Parcelas',
    code: 'EduParcelaData',
    label: 'EduParcelaData',
  },
  {
    key: 'RhuPessoaData',
    name: 'Pessoas',
    code: 'RhuPessoaData',
    label: 'RhuPessoaData',
  },
  {
    key: 'EduResponsavelAlunoData',
    name: 'Responsável do Aluno',
    code: 'EduResponsavelAlunoData',
    label: 'EduResponsavelAlunoData',
  },
  {
    key: 'RptReportsData',
    name: 'RM Reports (Relatórios)',
    code: 'RptReportsData',
    label: 'RptReportsData',
  },
  {
    key: 'EduPSUsuarioTipoRelacData',
    name: 'Responsável pelo Usuário',
    code: 'EduPSUsuarioTipoRelacData',
    label: 'EduPSUsuarioTipoRelacData',
  },
  {
    key: 'EduPSUsuarioData',
    name: 'Usuários da inscrição',
    code: 'EduPSUsuarioData',
    label: 'EduPSUsuarioData',
  },
  {
    key: 'GlbWorkflowData',
    name: 'Fórmula visual',
    code: 'GlbWorkflowData',
    label: 'GlbWorkflowData',
  },
  {
    key: 'GlbAtributoTipoData',
    name: 'Metadados: Tipo de Dados',
    code: 'GlbAtributoTipoData',
    label: 'GlbAtributoTipoData',
  },
  {
    key: 'GlbTabelaData',
    name: 'Metadados: Tabelas de Metadados',
    code: 'GlbTabelaData',
    label: 'GlbTabelaData',
  },
  {
    key: 'GlbProjetoData',
    name: 'Metadados: Projeto de Metadados',
    code: 'GlbProjetoData',
    label: 'GlbProjetoData',
  },
  {
    key: 'GlbMdNegocioData',
    name: 'Metadados: Modelo de Negócio',
    code: 'GlbMdNegocioData',
    label: 'GlbMdNegocioData',
  },
  {
    key: 'GlbRelacionamentoData',
    name: 'Metadados: Relacionamentos de Tabelas de Metadados',
    code: 'GlbRelacionamentoData',
    label: 'GlbRelacionamentoData',
  },
  {
    key: 'GlbApresentacaoData',
    name: 'Metadados: Apresentação de Metadados',
    code: 'GlbApresentacaoData',
    label: 'GlbApresentacaoData',
  },
];
